steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-k-412000/docker-repo/project-k', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-k-412000/docker-repo/project-k']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'project-k', '--image', 'gcr.io/project-k-412000/docker-repo/project-k', '--region', 'us-central1']
images:
- gcr.io/project-k-412000/docker-repo/project-k